package String_Programs;

/*
 public class Questions { 1)WAP TO CONVERT CHAR ARRAY INTO STRING WITHOUT
  USING BUILT IN ? 2)WAP TO CONVERT STRING INTO CHAR ARRAY ? 3)WAP TO REVERSE A
  STRING ? 4)WAP TO CHECK GIVEN STRING PALINDROME OR NOT ? 5)WAP TO CONVERT
 LOWERCASE VALUE INTO UPPERCASE ? 6)WAP TO CONVERT UPPERCASE VALUE INTO
  LOWERCAS ? 7)WAP TO CHECK WHETHER GIVEN CHARACTER IS PRESENT IN THE STRING OR
  NOT ? 8)WAP TO PRINT HOW MANY TIMES THE CHARACTER PRESENT IN A STRING ? 9)WAP
  TO COUNT VOWELS PRESENT IN A STRING ? 10)WAP TO COUNT CHARACTER PRESENT IN
 THE STRING ? 11)WAP TO COUNT CHARACTERS WITHOUT SPACE ? 12)WAP TO COUNT
 DIGITS PRESENT IN A STRING ? 13)WAP TO REMOVE SPACES IN THE SENTENCE ? 14)WAP
 TO COUNT WORDS PRESENT PRESENT IN A STRING ? 15)WAP TO REVERSE A WORD IN ITS
 * POSITION ? 16)WAP TO DELETE THE DUPLICATES CHARACTER PRESENT IN THE STRING ?
 * 17)WAP TO CHECK LARGEST SUBSTRING IN THE STRING ? 18)WAP TO FIND INDEX OF THE
 * CHARACTER IN THE STRING ? 19)WAP TO REMOVE VOWELS PRESENT IN THE ARRAY ?
 * 20)WAP TO STRING INTO INTEGER ? 21)WAP TO FIND THE WORD IN THE STRING ?
 * 22)WAP TO PRINT LARGEST WORD IN THE STRING ? }
 */
